var json = [
  {
    PK_MenuID: 53,
    name: "My Profile",
    get: "/UserProfile/Index",
    mid: 53,
    icon: "person",
  },
  {
    PK_MenuID: 52,
    name: "Dashboard",
    get: "/Workflow",
    mid: 52,
    icon: "dashboard",
  },
  {
    PK_MenuID: 1,
    name: "Administrative",
    get: "#collapseExample2",
    children: [
      {
        PK_MenuID: 101,
        name: "test",
        get: "test",
        mid: 101,
        icon: "drag_handle",
      },
      {
        PK_MenuID: 3,
        name: "Create User",
        get: "/Admin/CreateUsers",
        mid: 3,
        icon: "person_add",
      },
      {
        PK_MenuID: 10,
        name: "Create Role",
        get: "/Admin/CreateRoles",
        mid: 10,
        icon: "manage_accounts",
      },
      {
        PK_MenuID: 11,
        name: "Org. Chart",
        get: "/Admin/CreateOrganizationStructure",
        mid: 11,
        icon: "groups",
      },
      {
        PK_MenuID: 32,
        name: "Permission",
        get: "/Admin/Permission",
        mid: 32,
        icon: "how_to_reg",
      },
      {
        PK_MenuID: 88,
        name: "Departments",
        get: "/admin/Department",
        mid: 88,
        icon: "corporate_fare",
      },
      {
        PK_MenuID: 89,
        name: "Dpt Sections",
        get: "/admin/Sections",
        mid: 89,
        icon: "apartment",
      },
      {
        PK_MenuID: 97,
        name: "Create Menu",
        get: "/Admin/CreateMenu",
        mid: 97,
        icon: "menu",
      },
      {
        PK_MenuID: 2,
        name: "Create Step",
        get: "/Admin/CreateStep",
        mid: 2,
        icon: "account_tree",
      },
    ],
    mid: 1,
    icon: "settings",
  },
  {
    PK_MenuID: 12,
    name: "NPD",
    get: "#collapseExample3",
    children: [
      {
        PK_MenuID: 13,
        name: "Idea",
        get: "/Workflow/Ideas",
        mid: 13,
        icon: "lightbulb",
      },
      {
        PK_MenuID: 14,
        name: "My Task",
        get: "/Workflow/MyTask",
        mid: 14,
        icon: "assignment_late",
      },
      {
        PK_MenuID: 17,
        name: "My Request",
        get: "/Workflow/MyRequestTask",
        mid: 17,
        icon: "post_add",
      },
      {
        PK_MenuID: 18,
        name: "My Approval",
        get: "/Workflow/MyApproval",
        mid: 18,
        icon: "assignment_turned_in",
      },
      {
        PK_MenuID: 19,
        name: "My Participate",
        get: "/Workflow/Participate",
        mid: 19,
        icon: "assignment",
      },
    ],
    mid: 12,
    icon: "vaccines",
  },
  {
    PK_MenuID: 20,
    name: "CMMS",
    get: "#collapseExample5",
    children: [
      {
        PK_MenuID: 51,
        name: "Dashboard",
        get: "/Dashboard/CMMS",
        mid: 51,
        icon: "auto_awesome_mosaic",
      },
      {
        PK_MenuID: 21,
        name: "BM",
        get: "#collapseExample6",
        children: [
          {
            PK_MenuID: 22,
            name: "My Task",
            get: "/CMM/MyTask",
            mid: 22,
            icon: "assignment_late",
          },
          {
            PK_MenuID: 23,
            name: "My Request",
            get: "/CMM/MyRequest",
            mid: 23,
            icon: "post_add",
          },
          {
            PK_MenuID: 24,
            name: "My Approval",
            get: "/CMM/MyApproval",
            mid: 24,
            icon: "assignment_turned_in",
          },
          {
            PK_MenuID: 26,
            name: "Reports",
            get: "/CMM/CMMReports",
            mid: 26,
            icon: "summarize",
          },
        ],
        mid: 21,
        icon: "construction",
      },
      {
        PK_MenuID: 28,
        name: "PM",
        get: "#collapseExample6",
        children: [
          {
            PK_MenuID: 29,
            name: "My Task",
            get: "/PM/MyTask",
            mid: 29,
            icon: "assignment_late",
          },
          {
            PK_MenuID: 30,
            name: "Scheduler",
            get: "/PM/Scheduler",
            mid: 30,
            icon: "calendar_month",
          },
          {
            PK_MenuID: 31,
            name: "My Approval",
            get: "/PM/MyApproval",
            mid: 31,
            icon: "assignment_turned_in",
          },
        ],
        mid: 28,
        icon: "tune",
      },
      {
        PK_MenuID: 90,
        name: "Settings",
        get: "#collapseExample20",
        children: [
          {
            PK_MenuID: 92,
            name: "Machinery",
            get: "/CMM/Machinery",
            mid: 92,
            icon: "precision_manufacturing",
          },
          {
            PK_MenuID: 91,
            name: "Equipment",
            get: "/cmm/MachineEquipment_and_Area",
            mid: 91,
            icon: "event_seat",
          },
          {
            PK_MenuID: 93,
            name: "Task Type",
            get: "/cmm/CheckListTaskType",
            mid: 93,
            icon: "precision_manufacturing",
          },
        ],
        mid: 90,
        icon: "settings",
      },
    ],
    mid: 20,
    icon: "engineering",
  },
  {
    PK_MenuID: 33,
    name: "Approval Request",
    get: "#collapseExample8",
    children: [
      {
        PK_MenuID: 34,
        name: "My Task",
        get: "/BudgetApproval/MyTask",
        mid: 34,
        icon: "assignment_late",
      },
      {
        PK_MenuID: 35,
        name: "My Request",
        get: "/BudgetApproval/MyRequest",
        mid: 35,
        icon: "post_add",
      },
      {
        PK_MenuID: 36,
        name: "My Approval",
        get: "/BudgetApproval/MyApproval",
        mid: 36,
        icon: "assignment_turned_in",
      },
    ],
    mid: 33,
    icon: "assignment",
  },
  {
    PK_MenuID: 37,
    name: "TAF",
    get: "#collapseExample9",
    children: [
      {
        PK_MenuID: 38,
        name: "My Task",
        get: "/TAF/MyTask",
        mid: 38,
        icon: "assignment_late",
      },
      {
        PK_MenuID: 39,
        name: "My Request",
        get: "/TAF/MyRequest",
        mid: 39,
        icon: "post_add",
      },
      {
        PK_MenuID: 40,
        name: "My Approval",
        get: "/TAF/MyApproval",
        mid: 40,
        icon: "assignment_turned_in",
      },
    ],
    mid: 37,
    icon: "business_center",
  },
  {
    PK_MenuID: 41,
    name: "Art Work",
    get: "#collapseExample55",
    children: [
      {
        PK_MenuID: 42,
        name: "New Product",
        get: "#collapseExample10",
        children: [
          {
            PK_MenuID: 44,
            name: "My Task",
            get: "/ArtWork/MyTask",
            mid: 44,
            icon: "assignment_late",
          },
          {
            PK_MenuID: 45,
            name: "My Request",
            get: "/ArtWork/MyRequest",
            mid: 45,
            icon: "post_add",
          },
          {
            PK_MenuID: 46,
            name: "My Approval",
            get: "/ArtWork/MyApproval",
            mid: 46,
            icon: "assignment_turned_in",
          },
        ],
        mid: 42,
        icon: "medication",
      },
      {
        PK_MenuID: 43,
        name: "Revision",
        get: "#collapseExample11",
        mid: 43,
        icon: "published_with_changes",
      },
    ],
    mid: 41,
    icon: "draw",
  },
  {
    PK_MenuID: 47,
    name: "LS TAF",
    get: "#collapseExample12",
    children: [
      {
        PK_MenuID: 48,
        name: "My Task",
        get: "/LSTAF/MyTask",
        mid: 48,
        icon: "assignment_late",
      },
      {
        PK_MenuID: 49,
        name: "My Request",
        get: "/LSTAF/MyRequest",
        mid: 49,
        icon: "post_add",
      },
      {
        PK_MenuID: 50,
        name: "My Approval",
        get: "/LSTAF/MyApproval",
        mid: 50,
        icon: "assignment_turned_in",
      },
    ],
    mid: 47,
    icon: "airplane_ticket",
  },
  {
    PK_MenuID: 82,
    name: "LS TER",
    get: "#collapseExample13",
    children: [
      {
        PK_MenuID: 83,
        name: "MyTask",
        get: "/TER/MyTask",
        mid: 83,
        icon: "assignment_late",
      },
      {
        PK_MenuID: 84,
        name: "MyRequest",
        get: "/TER/MyRequest",
        mid: 84,
        icon: "post_add",
      },
      {
        PK_MenuID: 87,
        name: "MyApproval",
        get: "/TER/MyApproval",
        mid: 87,
        icon: "assignment_turned_in",
      },
    ],
    mid: 82,
    icon: "request_page",
  },
];
